   # docker from docker.com
    - name: check docker-compose already installed or not
      stat:
        path: /usr/local/bin/docker-compose
      register: dockercompose
    - debug:
        msg: "docker-compose exists..."
      when: dockercompose.stat.exists
    - name: copy docker install script
      copy:
        src: docker_ubuntu_install.sh
        dest: "{{ WORKING_DIRECTORY }}/docker_ubuntu_install.sh"
        mode: '755'
      when: not dockercompose.stat.exists and DOCKER_VERSION  == "docker.com"
    - name: install latest docker
      command: sh "{{ WORKING_DIRECTORY }}/docker_ubuntu_install.sh"
      when: not dockercompose.stat.exists  and  DOCKER_VERSION  == "docker.com"

    # docker from apt reops
    - name: install docker from apt repos
      apt:
        name:
          - 'docker-ce'
          - 'docker-compose'
        update_cache: yes
      when:  DOCKER_VERSION  == "apt"



